doctype: CRE
id: 148-435
links:
- document:
    doctype: CRE
    id: 003-004
    name: VALIDATE_BUSINESS_LOGIC_THREAT_MODEL
  type: SAM
- document:
    description: Verify that anti-automation controls are effective at mitigating
      breached credential testing, brute force, and account lockout attacks. Such
      controls include blocking the most common breached passwords, soft lockouts,
      rate limiting, CAPTCHA, ever increasing delays between attempts, IP address
      restrictions, or risk-based restrictions such as location, first login on a
      device, recent attempts to unlock the account, or similar. Verify that no more
      than 100 failed attempts per hour is possible on a single account.
    doctype: CRE
    id: 001-005-074
    name: ANTI_AUTOMATION_VALIDATE_DETECT_ANOMALIES
  type: SAM
- document:
    doctype: CRE
    id: 008-047-022
    name: VALIDATE_ORIGIN_CSRF_ANTI_AUTOMATION
  type: SAM
- document:
    doctype: CRE
    id: 003-004
    name: AUTHORIZE_FUNCTIONS_PER_USER
  type: SAM
- document:
    doctype: CRE
    id: 003-004
    name: MONITOR_ABUSE_BASED_ON_BUSINESS_LOGIC
  type: SAM
- document:
    doctype: CRE
    id: 008-004-055
    name: API_ANTI_AUTOMATION
  type: SAM
name: ANTI_AUTOMATION
