description: Verify that a generic message is shown when an unexpected or security
  sensitive error occurs, potentially with a unique ID which support personnel can
  use to investigate. (C10)
doctype: CRE
id: 004-015-036
links:
- document:
    doctype: CRE
    id: 127-263
    name: EXCEPTION_ERROR_HANDLING
  type: SAM
- document:
    doctype: CRE
    id: 736-939
    name: HARDEN
  type: SAM
- document:
    doctype: CRE
    id: 337-429
    name: HARDEN_INFO_DISCLOSURE
  type: SAM
- document:
    doctype: CRE
    id: 740-826
    name: CONFIGURATION
  type: SAM
- document:
    doctype: CRE
    id: 469-624
    name: CONFIG_SERVER
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: 'SI-5 Security Alerts, Advisories, and Directives, '
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: OPC
    section: C10
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html
    name: Cheatsheet
    section: Error Handling and Logging Verification Requirements
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: WSTG-ERRH-02
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: SIG ISO 25010
    section: Input and output verification
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: TOP10
    section: https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '210'
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: ASVS
    section: V7.4.1
    subsection: CONFIGURATION-CONFIG_SERVER-HARDEN-HARDEN_INFO_DISCLOSURE-EXCEPTION_ERROR_HANDLING
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: SI-11 Error Handling,
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: WSTG-ERRH-01
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html
    name: Cheatsheet
    section: Configuration Verification Requirements
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '209'
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: ASVS
    section: V14.3.1
    subsection: CONFIGURATION-CONFIG_SERVER-HARDEN-HARDEN_INFO_DISCLOSURE-EXCEPTION_ERROR_HANDLING
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: CM-6 CONFIGURATION SETTINGS
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: SI-11 ERROR HANDLING,
    subsection: ''
  type: SAM
name: CONFIGURATION_HARDENING_EXCEPTION_HANDLING_AVOID_INFO_DISCLOSURE
