doctype: CRE
id: 001-002-005
links:
- document:
    doctype: CRE
    id: 613-579
    name: ACCESS_CONTROL
  type: SAM
- document:
    doctype: CRE
    id: 736-939
    name: HARDEN
  type: SAM
- document:
    doctype: CRE
    id: 253-303
    name: ADMINISTRATIVE/ADMIN_TASKS
  type: SAM
- document:
    doctype: CRE
    id: 861-431
    name: DIRECTORY_BROWSING
  type: SAM
- document:
    doctype: CRE
    id: 337-429
    name: HARDEN_INFO_DISCLOSURE
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: CM-6 CONFIGURATION SETTINGS,
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/REST_Assessment_Cheat_Sheet.html
    name: Cheatsheet
    section: Access Control Verification Requirements
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: WSTG-CONF-03
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: SIG ISO 25010
    section: Input and output verification
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: TOP10
    section: https://owasp.org/www-project-top-ten/2017/A5_2017-Broken_Access_Control
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '548'
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: ASVS
    section: V4.3.2
    subsection: ACCESS_CONTROL-ADMINISTRATIVE/ADMIN_TASKS-HARDEN-DIRECTORY_BROWSING-HARDEN_INFO_DISCLOSURE
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: CM-7 LEAST FUNCTIONALITY
    subsection: ''
  type: SAM
name: CONFIGURATION_HARDENING_SERVER_DIRECTORY_BROWSING
