doctype: CRE
id: 469-624
links:
- document:
    description: Verify that a generic message is shown when an unexpected or security
      sensitive error occurs, potentially with a unique ID which support personnel
      can use to investigate. (C10)
    doctype: CRE
    id: 004-015-036
    name: CONFIGURATION_HARDENING_EXCEPTION_HANDLING_AVOID_INFO_DISCLOSURE
  type: SAM
- document:
    description: Verify that server configuration is hardened as per the recommendations
      of the application server and frameworks in use.
    doctype: CRE
    id: 004-015-034
    name: CONFIGURATION_HARDENING_SERVER
  type: SAM
- document:
    description: Verify that web or application server and application framework debug
      modes are disabled in production to eliminate debug features, developer consoles,
      and unintended security disclosures.
    doctype: CRE
    id: 004-015-036
    name: CONFIGURATION_HARDENING_DISABLE_DEBUG_MODE_AVOID_INFO_DISCLOSURE
  type: SAM
- document:
    description: Verify that the HTTP headers or any part of the HTTP response do
      not expose detailed version information of system components.
    doctype: CRE
    id: 004-015-036
    name: SANITIZE_OUTPUT_HTTP_HEADERS_RESPONSE_AVOID_INFO_DISCLOSURE
  type: SAM
- document:
    description: Verify that every HTTP response contains a content type header specifying
      a safe character set (e.g., UTF-8, ISO 8859-1).
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_CONTENT_TYPE_CHARACTER_SET
  type: SAM
- document:
    description: 'Verify that all API responses contain Content-Disposition: attachment;
      filename="api.json" (or other appropriate filename for the content type).'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_CONTENT_TYPE
  type: SAM
- document:
    description: Verify that a content security policy (CSPv2) is in place that helps
      mitigate impact for XSS attacks like HTML, DOM, JSON, and JavaScript injection
      vulnerabilities.
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_CSP
  type: SAM
- document:
    description: 'Verify that all responses contain X-Content-Type-Options: nosniff.'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_NOSNIFF
  type: SAM
- document:
    description: 'Verify that HTTP Strict Transport Security headers are included
      on all responses and for all subdomains, such as Strict-Transport-Security:
      max-age=15724800; includeSubdomains.'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADER_HSTS
  type: SAM
- document:
    description: Verify that a suitable "Referrer-Policy" header is included, such
      as "no-referrer" or "same-origin".
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADER_REFERRER_POLICY
  type: SAM
- document:
    description: 'Verify that a suitable X-Frame-Options or Content-Security-Policy:
      frame-ancestors header is in use for sites where content should not be embedded
      in a third-party site.'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_FRAME
  type: SAM
- document:
    description: Verify that the cross-domain resource sharing (CORS) Access-Control-Allow-Origin
      header uses a strict white-list of trusted domains to match against and does
      not support the "null" origin.
    doctype: CRE
    id: 004-015-039
    name: VALIDATE_HTTP_HEADERS_CORS_WHITELIST
  type: SAM
name: CONFIG_SERVER
