doctype: CRE
id: 740-826
links:
- document:
    description: Verify that encryption initialization vector, cipher configuration,
      and block modes are configured securely using the latest advice.
    doctype: CRE
    id: 005-021-025
    name: ENCRYPT_DATA_AT_REST_CRYPTOGRAPHIC_DIRECTIVES_SECURE_CONFIGURATION
  type: SAM
- document:
    doctype: CRE
    id: 004-015-036
    name: PROTECT_DATA_IN_TRANSIT_TLS_HEADERS_PAYLOAD
  type: SAM
- document:
    doctype: CRE
    id: 002-026-031
    name: CONFIGURATION_CODE_PIPELINE_TRACEABILITY
  type: SAM
- document:
    doctype: CRE
    id: 009-027
    name: CONFIGURATION_DEPLOY_UNTRUSTED_DEVICES_VALIDATE_BINARY_ENDPOINTS_INTEGRITY
  type: SAM
- document:
    doctype: CRE
    id: 002-018
    name: CONFIGURATION_THIRD_PARTY_DEPENDENCIES_FRESHNESS_ALERTING_PIPELINE
  type: SAM
- document:
    doctype: CRE
    id: 002-018
    name: CONFIGURATION_CODE_PIPELINE_DEPLOYMENT_AUTOMATION_VERIFY_DEPLOYMENT
  type: SAM
- document:
    description: Verify that application deployments adequately sandbox, containerize
      and/or isolate at the network level to delay and deter attackers from attacking
      other applications, especially when they are performing sensitive or dangerous
      actions such as deserialization. (C5)
    doctype: CRE
    id: 005-022-025
    name: CONFIGURATION_DEPLOYMENT_ISOLATE_NETWERK_LEVEL
  type: SAM
- document:
    doctype: CRE
    id: 005-022-025
    name: CONFIGURATION_THIRD_PARTY_DEPENDENCIES_NO_DEPRECATED/INSECURE_CLIENTSIDE_TECHNOLOGIES
  type: SAM
- document:
    description: Verify that a generic message is shown when an unexpected or security
      sensitive error occurs, potentially with a unique ID which support personnel
      can use to investigate. (C10)
    doctype: CRE
    id: 004-015-036
    name: CONFIGURATION_HARDENING_EXCEPTION_HANDLING_AVOID_INFO_DISCLOSURE
  type: SAM
- document:
    doctype: CRE
    id: 004-012-013
    name: CONFIGURATION_CODE_SCAN_MALICIOUS_CONTENT
  type: SAM
- document:
    doctype: CRE
    id: 004-012-050
    name: CONFIGURATION_CODE_THIRD_PARTY_DEPENDENCIES_SCAN_MALICIOUS_CONTENT
  type: SAM
- document:
    doctype: CRE
    id: 004-012-050
    name: CONFIGURATION_VERIFY_PRIVACY_PERMISSIONS
  type: SAM
- document:
    doctype: CRE
    id: 004-012-061
    name: CONFIGURATION_VALIDATE_CODE_INTEGRITY_UPDATES
  type: SAM
- document:
    doctype: CRE
    id: 004-012-061
    name: CONFIGURATION_VALIDATE_CODE_INTEGRITY_SIGNATURES
  type: SAM
- document:
    description: Verify that the application has protection from sub-domain takeovers
      if the application relies upon DNS entries or DNS sub-domains, such as expired
      domain names, out of date DNS pointers or CNAMEs, expired projects at public
      source code repos, or transient cloud APIs, serverless functions, or storage
      buckets (autogen-bucket-id.cloud.example.com) or similar. Protections can include
      ensuring that DNS names used by applications are regularly checked for expiry
      or change.
    doctype: CRE
    id: 004-012-061
    name: CONFIGURATION_HARDENING_SERVER_VALIDATE_DNS
  type: SAM
- document:
    doctype: CRE
    id: 004-006-012
    name: CONFIGURATION_CODE_PIPELINE_DEPLOYMENT_AUTOMATION
  type: SAM
- document:
    description: Verify that compiler flags are configured to enable all available
      buffer overflow protections and warnings, including stack randomization, data
      execution prevention, and to break the build if an unsafe pointer, memory, format
      string, integer, or string operations are found.
    doctype: CRE
    id: 004-006-017
    name: CONFIGURATION_CODE_HARDENING_COMPILER_FLAGS
  type: SAM
- document:
    description: Verify that server configuration is hardened as per the recommendations
      of the application server and frameworks in use.
    doctype: CRE
    id: 004-015-034
    name: CONFIGURATION_HARDENING_SERVER
  type: SAM
- document:
    doctype: CRE
    id: 004-006-018
    name: CONFIGURATION_CODE_INTEGRITY
  type: SAM
- document:
    description: Verify that all components are up to date, preferably using a dependency
      checker during build or compile time. (C2)
    doctype: CRE
    id: 004-019-032
    name: CONFIGURATION_THIRD_PARTY_DEPENDENCIES_FRESHNESS
  type: SAM
- document:
    description: Verify that all unneeded features, documentation, samples, configurations
      are removed, such as sample applications, platform documentation, and default
      or example users.
    doctype: CRE
    id: 004-019-035
    name: CONFIGURATION_THIRD_PARTY_DEPENDENCIES_HARDENING
  type: SAM
- document:
    doctype: CRE
    id: 004-019-041
    name: THIRD_PARTY_DEPENDENCIES-USE_SRI_FOR_CDNS
  type: SAM
- document:
    description: Verify that third party components come from pre-defined, trusted
      and continually maintained repositories. (C2)
    doctype: CRE
    id: 004-019-042
    name: THIRD_PARTY_DEPENDENCIES_TRUSTED_ORIGIN
  type: SAM
- document:
    description: Verify that an inventory catalog is maintained of all third party
      libraries in use. (C2)
    doctype: CRE
    id: 004-019-044
    name: THIRD_PARTY_DEPENDENCIES_INVENTORY
  type: SAM
- document:
    description: Verify that the attack surface is reduced by sandboxing or encapsulating
      third party libraries to expose only the required behaviour into the application.
      (C2)
    doctype: CRE
    id: 004-019-037
    name: THIRD_PARTY_DEPENDENCIES_LIMIT_ATTACK_SURFACE
  type: SAM
- document:
    description: Verify that web or application server and application framework debug
      modes are disabled in production to eliminate debug features, developer consoles,
      and unintended security disclosures.
    doctype: CRE
    id: 004-015-036
    name: CONFIGURATION_HARDENING_DISABLE_DEBUG_MODE_AVOID_INFO_DISCLOSURE
  type: SAM
- document:
    description: Verify that the HTTP headers or any part of the HTTP response do
      not expose detailed version information of system components.
    doctype: CRE
    id: 004-015-036
    name: SANITIZE_OUTPUT_HTTP_HEADERS_RESPONSE_AVOID_INFO_DISCLOSURE
  type: SAM
- document:
    description: Verify that every HTTP response contains a content type header specifying
      a safe character set (e.g., UTF-8, ISO 8859-1).
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_CONTENT_TYPE_CHARACTER_SET
  type: SAM
- document:
    description: 'Verify that all API responses contain Content-Disposition: attachment;
      filename="api.json" (or other appropriate filename for the content type).'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_CONTENT_TYPE
  type: SAM
- document:
    description: Verify that a content security policy (CSPv2) is in place that helps
      mitigate impact for XSS attacks like HTML, DOM, JSON, and JavaScript injection
      vulnerabilities.
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_CSP
  type: SAM
- document:
    description: 'Verify that all responses contain X-Content-Type-Options: nosniff.'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_NOSNIFF
  type: SAM
- document:
    description: 'Verify that HTTP Strict Transport Security headers are included
      on all responses and for all subdomains, such as Strict-Transport-Security:
      max-age=15724800; includeSubdomains.'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADER_HSTS
  type: SAM
- document:
    description: Verify that a suitable "Referrer-Policy" header is included, such
      as "no-referrer" or "same-origin".
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADER_REFERRER_POLICY
  type: SAM
- document:
    description: 'Verify that a suitable X-Frame-Options or Content-Security-Policy:
      frame-ancestors header is in use for sites where content should not be embedded
      in a third-party site.'
    doctype: CRE
    id: 004-015-038
    name: CONFIGURATION_SET_HEADERS_FRAME
  type: SAM
- document:
    description: Verify that the cross-domain resource sharing (CORS) Access-Control-Allow-Origin
      header uses a strict white-list of trusted domains to match against and does
      not support the "null" origin.
    doctype: CRE
    id: 004-015-039
    name: VALIDATE_HTTP_HEADERS_CORS_WHITELIST
  type: SAM
name: CONFIGURATION
