description: Verify that encryption initialization vector, cipher configuration, and
  block modes are configured securely using the latest advice.
doctype: CRE
id: 005-021-025
links:
- document:
    doctype: CRE
    id: 673-960
    name: CRYPTOGRAPHIC_DIRECTIVES
  type: SAM
- document:
    doctype: CRE
    id: 184-331
    name: DATA_PROTECTION
  type: SAM
- document:
    doctype: CRE
    id: 607-193
    name: ENCRYPT_DATA_AT_REST
  type: SAM
- document:
    doctype: CRE
    id: 740-826
    name: CONFIGURATION
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: IA-5 AUTHENTICATOR MANAGEMENT,
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html,https://cheatsheetseries.owasp.org/cheatsheets/Key_Management_Cheat_Sheet.html
    name: Cheatsheet
    section: Stored Cryptography Verification Requirements
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: WSTG-CRYP-04
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: SIG ISO 25010
    section: Secure data storage
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: TOP10
    section: https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '326'
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: ASVS
    section: V6.2.3
    subsection: DATA_PROTECTION-ENCRYPT_DATA_AT_REST-CRYPTOGRAPHIC_DIRECTIVES-CONFIGURATION
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: SC-12 CRYPTOGRAPHIC KEY ESTABLISHMENT AND MANAGEMENT,
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: SC-13 CRYPTOGRAPHIC PROTECTION
    subsection: ''
  type: SAM
name: ENCRYPT_DATA_AT_REST_CRYPTOGRAPHIC_DIRECTIVES_SECURE_CONFIGURATION
