doctype: CRE
id: 518-927
links:
- document:
    description: Verify the use of a secure software development lifecycle that addresses
      security in all stages of development. (C1)
    doctype: CRE
    id: 002-036-10
    name: SDLC_APPLY_CONSISTENTLY
  type: SAM
- document:
    description: Verify the use of threat modeling for every design change or sprint
      planning to identify threats, plan for countermeasures, facilitate appropriate
      risk responses, and guide security testing.
    doctype: CRE
    id: 002-036-1
    name: ARCHITECTURE_DESIGN_CHANGE_THREAT_MODEL
  type: SAM
- document:
    description: Verify that all user stories and features contain functional security
      constraints, such as "As a user, I should be able to view and edit my profile.
      I should not be able to view or edit anyone else's profile"
    doctype: CRE
    id: 002-036-2
    name: SDLC_FEATURES_SECURITY_CONSTRAINTS_
  type: SAM
- document:
    description: Verify documentation and justification of all the application's trust
      boundaries, components, and significant data flows.
    doctype: CRE
    id: 002-036-3
    name: ARCHITECTURE_VERIFY_COMPONENTS_AND_CONNECTIONS_DOCUMENTATION
  type: SAM
- document:
    description: Verify definition and security analysis of the application's high-level
      architecture and all connected remote services. (C1)
    doctype: CRE
    id: 002-036-4
    name: ARCHITECTURE_VERIFY_COMPONENTS_AND_CONNECTIONS
  type: SAM
- document:
    description: Verify availability of a secure coding checklist, security requirements,
      guideline, or policy to all developers and testers.
    doctype: CRE
    id: 002-036-5
    name: SDLC_GUIDELINES_DEVELOPERS_SECURE_CODING
  type: SAM
- document:
    doctype: CRE
    id: 004-006-022
    name: SDLC_DEFINE_INPUT_OUTPUT_REQUIREMENTS
  type: SAM
name: REQUIREMENTS
