description: "Verify the application does not treat OAuth and refresh tokens \u2014\
  \ on their own \u2014 as the presence of the subscriber and allows users to terminate\
  \ trust relationships with linked applications."
doctype: CRE
id: 011-040-069
links:
- document:
    doctype: CRE
    id: 780-769
    name: SESSION_TERMINATION
  type: SAM
- document:
    doctype: CRE
    id: 636-456
    name: SESSION_MANAGEMENT
  type: SAM
- document:
    doctype: CRE
    id: 842-154
    name: TOKEN_DIRECTIVES
  type: SAM
- document:
    doctype: CRE
    id: 684-837
    name: STATELESS_TOKEN_BASED
  type: SAM
- document:
    doctype: CRE
    id: 706-127
    name: REFRESH_TOKEN/OAUTH
  type: SAM
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html,https://cheatsheetseries.owasp.org/cheatsheets/Transaction_Authorization_Cheat_Sheet.html
    name: Cheatsheet
    section: Session Management Verification Requirements
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-63
    section: 7.1.2
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: SIG ISO 25010
    section: Session management
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: TOP10
    section: https://owasp.org/www-project-top-ten/2017/A5_2017-Broken_Access_Control
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '290'
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: ASVS
    section: V3.5.1
    subsection: SESSION_MANAGEMENT-TOKEN_DIRECTIVES-STATELESS_TOKEN_BASED-SESSION_TERMINATION-REFRESH_TOKEN/OAUTH
  type: SAM
name: SESSION_MANAGEMENT_STATELESS_TOKENS_TERMINATE_TRUST_LINKED_APPLICATION
