doctype: CRE
id: 872-444
links:
- document:
    description: Verify that XSD schema validation takes place to ensure a properly
      formed XML document, followed by validation of each input field before any processing
      of that data takes place.
    doctype: CRE
    id: 008-046-067
    name: VALIDATE_API_XSD_SCHEMA
  type: SAM
- document:
    doctype: CRE
    id: 008-046-067
    name: VALIDATE_ORIGIN_API_SOAP_WS_SECURITY
  type: SAM
name: SOAP_DIRECTIVES_XSD_SCHEMA_WS_SECURITY
