name: Sync
on:
  schedule:
    - cron: '* * * * *'  # every minute
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
    - name: Setup
      uses: actions/setup-python@v2
    - name: Run
      env: 
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_API_KEY: ${{ secrets.API_KEY }}
      run: |

        mkdir -p ~/.ssh ~/.config/gspread
        ssh-keyscan github.com > ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 0500 ~/.ssh/id_rsa

        echo $GITHUB_ACTOR
        # wc -c ${{secrets.GITHUB_TOKEN}}
        # default checkout clones https, need to somehow set the ssh url
        git remote set-url origin northdpole:${{secrets.GITHUB_TOKEN}}@github.com:northdpole/www-project-integration-standards.git

        ls -lah
        git remote -v

        pip3 install --user -r scripts/cre_sync/requirements.txt 
        echo "$SERVICE_ACCOUNT" > ~/.config/gspread/service_account.json

        git config --global user.email "cre_bot@sgaster.me"
        git config --global user.name "cre bot"
        # todo since i have git, replace ssh with https://uname:token@github.com/path remote

        python3 scripts/cre_sync/spreadsheet_to_yaml.py
