name: Sync
on:
  schedule:
    - cron: '0 1 * * *'  # every day
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
    - name: Setup
      uses: actions/setup-python@v2
    - name: Run
      env: 
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_API_KEY: ${{ secrets.API_TOKEN }}
      run: |

        mkdir -p ~/.ssh ~/.config/gspread
        ssh-keyscan github.com > ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 0500 ~/.ssh/id_rsa


        git remote set-url origin git@github.com:northdpole/www-project-integration-standards.git
        git pull origin master


        pip3 install --user -r scripts/cre_sync/requirements.txt 
        echo "$SERVICE_ACCOUNT" > ~/.config/gspread/service_account.json

        git config --global user.email "cre_bot@sgaster.me"
        git config --global user.name "cre bot"
        # following does not work, try again sometime in the future 
        # todo since i have git, replace ssh with https://uname:token@github.com/path remote

        python3 scripts/cre_sync/spreadsheet_to_yaml.py
