name: Sync
on:
  schedule:
    - cron: '* * * * *'  # every minute
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
    - name: Setup
      uses: actions/setup-python@v2
    - name: Run
      env: 
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GITHUB_API_KEY: ${{ secrets.API_KEY }}
      run: |

        mkdir -p ~/.ssh ~/.config/gspread
        ssh-keyscan github.com > ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 511 ~/.ssh/id_rsa

        ls -lah
        git status
        ssh git@github.com

        pip3 install --user -r scripts/cre_sync/requirements.txt 
        echo "$SERVICE_ACCOUNT" > ~/.config/gspread/service_account.json

        python3 scripts/cre_sync/spreadsheet_to_yaml.py
